### ISSUE TITLE
Incompatible license & stealing of Hyperium's event system.

### ISSUE THREAD

**Issue by ghost** [Evergreen-Client/Evergreen-1.8.9#2]
You should probably know that you are not allowed to include code licensed under LGPL into an Apache-licensed project. In this case, that includes the Hyperium event system & probably more. I recommend you remove our event system and learn to make your own, instead of just "switching the license" so you don't have to do any work and continue to ransack off of Hyperium like everyone else seems to do these days.

**Comment by ghost** [comment]
While at it, noticed you also practically stole Forge's command handler, which is also under LGPL.

**Comment by isXander** [comment]
> While at it, noticed you also practically stole Forge's command handler, which is also under LGPL.

I don't see how a command handler, which consists of "does message start with / if so, look in a map of commands and pick right one". I am currently working on an event system myself, just there to get a working prototype, forgot about licensing issues, sorry!

**Comment by solonovamax** [comment]
You closed this and yet you never fixed the issue.

**Comment by isXander** [comment]
@asbyth @solonovamax 

New EventBus has been made,

**Comment by solonovamax** [comment]
Dude, you're literally still using the same code, with just some minor changes.

**Comment by isXander** [comment]
> Dude, you're literally still using the same code, with just some minor changes.

It is literally made from scratch. That's why it is bad
